sudo: required
services:
  - docker

before_install:
  - docker build -t pgrant87/docker-react-1 -f Dockerfile.dev .

script:
  - docker run -e CI=true  pgrant87/docker-react-1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

